### ISSUE TITLE
保存的方法 save,一直搞不明白this.isNew在哪里定义的？一保存就判断了吗

### ISSUE THREAD

**Issue by Niofh** [kvkens/Imooc#1]
MovieSchema.pre("save", function(next) {
    if (this.isNew) {
        this.meta.createAt = this.meta.updateAt = Date.now();
    } else {
        this.meta.updateAt = Date.now();
    }
    next()
});

**Comment by kvkens** [comment]
这个this.isNew方法是ORM模型Mongoose里面继承来的方法，我们用的时候就已经从父类继承来的，所以说看不到定义，但是可以使用。
